name: wind_power_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.3
  - numpy>=1.21
  - matplotlib>=3.5
  - scikit-learn>=1.0
  - statsmodels>=0.13
  - scipy>=1.7
  - pywavelets>=1.4
  - pip
  - pip:
    - PyEMD>=0.5
    - tensorflow>=2.8
