name: wind_power_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas>=1.3.0
  - numpy>=1.21.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scikit-learn>=1.0.0
  - jupyter
  - pip
  - pip:
    - tensorflow>=2.8.0
    - joblib>=1.1.0
    - PyEMD>=0.5.0
    - PyWavelets>=1.4.0
    - statsmodels>=0.13.0
    - scipy>=1.7.0
